---
#- name: "Stop si besoin"
#  import_tasks: "tomcat-stop.yml"

- name: "Mise en place des prérequis"
  import_tasks: "tomcat-require.yml"

- name: "Download et Unzip de Tomcat"
  import_tasks: "tomcat-dl-unzip.yml"

- name: "Installation"
  import_tasks: "tomcat-install.yml"

#- name: "Deploiement du War"
#  import_tasks: "tomcat-deploy-war.yml"

- name: "Start Tomcat"
  import_tasks: "tomcat-start.yml"