---
- name: Unzip archives on /opt/tomcat
  unarchive:
    src: http://apache.mediamirrors.org/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13.tar.gz
    dest: /opt/tomcat
    remote_src: yes

#Make tomcat owner
- name: Tomcat Owner of webapps
  file: dest=/opt/tomcat/webapps owner=tomcat recurse=yes
- name: Tomcat Owner of work
  file: dest=/opt/tomcat/work owner=tomcat recurse=yes
  - name: Tomcat Owner of temp
  file: dest=/opt/tomcat/temp owner=tomcat recurse=yes
  - name: Tomcat Owner of logs
  file: dest=/opt/tomcat/logs owner=tomcat recurse=yes